export const FETCH_STUFF = 'FETCH_STUFF'
export const RECEIVE_STUFF = 'RECEIVE_STUFF'

export const SET_CURSOR = 'SET_CURSOR'
export const SET_EDITING = 'SET_EDITING'
export const RESET_STARTING_EDITOR_VALUE = 'RESET_STARTING_EDITOR_VALUE'
export const SET_VALUE = 'SET_VALUE'

export const SCROLL_UP = 'SCROLL_UP'
export const SCROLL_DOWN = 'SCROLL_DOWN'
export const SCROLL_LEFT = 'SCROLL_LEFT'
export const SCROLL_RIGHT = 'SCROLL_RIGHT'

export const TOGGLE_SHIFT_GRID = 'TOGGLE_SHIFT_GRID'

export const REFRESH_VIEWPORT = 'REFRESH_VIEWPORT'