export const FETCH_STUFF = 'FETCH_STUFF'
export const RECEIVE_STUFF = 'RECEIVE_STUFF'

export const SET_CURSOR = 'SET_CURSOR'
export const SET_EDITING = 'SET_EDITING'
export const SET_VALUE = 'SET_VALUE'
export const RESET_STARTING_VALUE = 'RESET_STARTING_VALUE'
export const TOGGLE_SHIFT_GRID = 'TOGGLE_SHIFT_GRID'
